// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.stevenpg.rvg;

/**
 * Protobuf type {@code com.stevenpg.rvg.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.stevenpg.rvg.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.stevenpg.rvg.Message.Car.Builder subBuilder = null;
            if (car_ != null) {
              subBuilder = car_.toBuilder();
            }
            car_ = input.readMessage(com.stevenpg.rvg.Message.Car.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(car_);
              car_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.stevenpg.rvg.Message.Driver.Builder subBuilder = null;
            if (driver_ != null) {
              subBuilder = driver_.toBuilder();
            }
            driver_ = input.readMessage(com.stevenpg.rvg.Message.Driver.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(driver_);
              driver_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stevenpg.rvg.MessageOuterClass.internal_static_com_stevenpg_rvg_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stevenpg.rvg.MessageOuterClass.internal_static_com_stevenpg_rvg_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stevenpg.rvg.Message.class, com.stevenpg.rvg.Message.Builder.class);
  }

  public interface CarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stevenpg.rvg.Message.Car)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string make = 1;</code>
     * @return The make.
     */
    java.lang.String getMake();
    /**
     * <code>string make = 1;</code>
     * @return The bytes for make.
     */
    com.google.protobuf.ByteString
        getMakeBytes();

    /**
     * <code>string model = 2;</code>
     * @return The model.
     */
    java.lang.String getModel();
    /**
     * <code>string model = 2;</code>
     * @return The bytes for model.
     */
    com.google.protobuf.ByteString
        getModelBytes();

    /**
     * <code>string trim = 3;</code>
     * @return The trim.
     */
    java.lang.String getTrim();
    /**
     * <code>string trim = 3;</code>
     * @return The bytes for trim.
     */
    com.google.protobuf.ByteString
        getTrimBytes();

    /**
     * <code>string color = 4;</code>
     * @return The color.
     */
    java.lang.String getColor();
    /**
     * <code>string color = 4;</code>
     * @return The bytes for color.
     */
    com.google.protobuf.ByteString
        getColorBytes();

    /**
     * <code>uint32 year = 5;</code>
     * @return The year.
     */
    int getYear();

    /**
     * <code>uint32 mileage = 6;</code>
     * @return The mileage.
     */
    int getMileage();
  }
  /**
   * Protobuf type {@code com.stevenpg.rvg.Message.Car}
   */
  public static final class Car extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.stevenpg.rvg.Message.Car)
      CarOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Car.newBuilder() to construct.
    private Car(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Car() {
      make_ = "";
      model_ = "";
      trim_ = "";
      color_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Car();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Car(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              make_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              model_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              trim_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              color_ = s;
              break;
            }
            case 40: {

              year_ = input.readUInt32();
              break;
            }
            case 48: {

              mileage_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stevenpg.rvg.MessageOuterClass.internal_static_com_stevenpg_rvg_Message_Car_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stevenpg.rvg.MessageOuterClass.internal_static_com_stevenpg_rvg_Message_Car_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stevenpg.rvg.Message.Car.class, com.stevenpg.rvg.Message.Car.Builder.class);
    }

    public static final int MAKE_FIELD_NUMBER = 1;
    private volatile java.lang.Object make_;
    /**
     * <code>string make = 1;</code>
     * @return The make.
     */
    @java.lang.Override
    public java.lang.String getMake() {
      java.lang.Object ref = make_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        make_ = s;
        return s;
      }
    }
    /**
     * <code>string make = 1;</code>
     * @return The bytes for make.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMakeBytes() {
      java.lang.Object ref = make_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        make_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODEL_FIELD_NUMBER = 2;
    private volatile java.lang.Object model_;
    /**
     * <code>string model = 2;</code>
     * @return The model.
     */
    @java.lang.Override
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      }
    }
    /**
     * <code>string model = 2;</code>
     * @return The bytes for model.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRIM_FIELD_NUMBER = 3;
    private volatile java.lang.Object trim_;
    /**
     * <code>string trim = 3;</code>
     * @return The trim.
     */
    @java.lang.Override
    public java.lang.String getTrim() {
      java.lang.Object ref = trim_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        trim_ = s;
        return s;
      }
    }
    /**
     * <code>string trim = 3;</code>
     * @return The bytes for trim.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTrimBytes() {
      java.lang.Object ref = trim_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        trim_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLOR_FIELD_NUMBER = 4;
    private volatile java.lang.Object color_;
    /**
     * <code>string color = 4;</code>
     * @return The color.
     */
    @java.lang.Override
    public java.lang.String getColor() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        color_ = s;
        return s;
      }
    }
    /**
     * <code>string color = 4;</code>
     * @return The bytes for color.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getColorBytes() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int YEAR_FIELD_NUMBER = 5;
    private int year_;
    /**
     * <code>uint32 year = 5;</code>
     * @return The year.
     */
    @java.lang.Override
    public int getYear() {
      return year_;
    }

    public static final int MILEAGE_FIELD_NUMBER = 6;
    private int mileage_;
    /**
     * <code>uint32 mileage = 6;</code>
     * @return The mileage.
     */
    @java.lang.Override
    public int getMileage() {
      return mileage_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMakeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, make_);
      }
      if (!getModelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, model_);
      }
      if (!getTrimBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, trim_);
      }
      if (!getColorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, color_);
      }
      if (year_ != 0) {
        output.writeUInt32(5, year_);
      }
      if (mileage_ != 0) {
        output.writeUInt32(6, mileage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMakeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, make_);
      }
      if (!getModelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, model_);
      }
      if (!getTrimBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, trim_);
      }
      if (!getColorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, color_);
      }
      if (year_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, year_);
      }
      if (mileage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, mileage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stevenpg.rvg.Message.Car)) {
        return super.equals(obj);
      }
      com.stevenpg.rvg.Message.Car other = (com.stevenpg.rvg.Message.Car) obj;

      if (!getMake()
          .equals(other.getMake())) return false;
      if (!getModel()
          .equals(other.getModel())) return false;
      if (!getTrim()
          .equals(other.getTrim())) return false;
      if (!getColor()
          .equals(other.getColor())) return false;
      if (getYear()
          != other.getYear()) return false;
      if (getMileage()
          != other.getMileage()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAKE_FIELD_NUMBER;
      hash = (53 * hash) + getMake().hashCode();
      hash = (37 * hash) + MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getModel().hashCode();
      hash = (37 * hash) + TRIM_FIELD_NUMBER;
      hash = (53 * hash) + getTrim().hashCode();
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
      hash = (37 * hash) + MILEAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMileage();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stevenpg.rvg.Message.Car parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stevenpg.rvg.Message.Car parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stevenpg.rvg.Message.Car parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stevenpg.rvg.Message.Car parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stevenpg.rvg.Message.Car parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stevenpg.rvg.Message.Car parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stevenpg.rvg.Message.Car parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stevenpg.rvg.Message.Car parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stevenpg.rvg.Message.Car parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stevenpg.rvg.Message.Car parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stevenpg.rvg.Message.Car parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stevenpg.rvg.Message.Car parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stevenpg.rvg.Message.Car prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.stevenpg.rvg.Message.Car}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stevenpg.rvg.Message.Car)
        com.stevenpg.rvg.Message.CarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stevenpg.rvg.MessageOuterClass.internal_static_com_stevenpg_rvg_Message_Car_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stevenpg.rvg.MessageOuterClass.internal_static_com_stevenpg_rvg_Message_Car_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stevenpg.rvg.Message.Car.class, com.stevenpg.rvg.Message.Car.Builder.class);
      }

      // Construct using com.stevenpg.rvg.Message.Car.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        make_ = "";

        model_ = "";

        trim_ = "";

        color_ = "";

        year_ = 0;

        mileage_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stevenpg.rvg.MessageOuterClass.internal_static_com_stevenpg_rvg_Message_Car_descriptor;
      }

      @java.lang.Override
      public com.stevenpg.rvg.Message.Car getDefaultInstanceForType() {
        return com.stevenpg.rvg.Message.Car.getDefaultInstance();
      }

      @java.lang.Override
      public com.stevenpg.rvg.Message.Car build() {
        com.stevenpg.rvg.Message.Car result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.stevenpg.rvg.Message.Car buildPartial() {
        com.stevenpg.rvg.Message.Car result = new com.stevenpg.rvg.Message.Car(this);
        result.make_ = make_;
        result.model_ = model_;
        result.trim_ = trim_;
        result.color_ = color_;
        result.year_ = year_;
        result.mileage_ = mileage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stevenpg.rvg.Message.Car) {
          return mergeFrom((com.stevenpg.rvg.Message.Car)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stevenpg.rvg.Message.Car other) {
        if (other == com.stevenpg.rvg.Message.Car.getDefaultInstance()) return this;
        if (!other.getMake().isEmpty()) {
          make_ = other.make_;
          onChanged();
        }
        if (!other.getModel().isEmpty()) {
          model_ = other.model_;
          onChanged();
        }
        if (!other.getTrim().isEmpty()) {
          trim_ = other.trim_;
          onChanged();
        }
        if (!other.getColor().isEmpty()) {
          color_ = other.color_;
          onChanged();
        }
        if (other.getYear() != 0) {
          setYear(other.getYear());
        }
        if (other.getMileage() != 0) {
          setMileage(other.getMileage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stevenpg.rvg.Message.Car parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stevenpg.rvg.Message.Car) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object make_ = "";
      /**
       * <code>string make = 1;</code>
       * @return The make.
       */
      public java.lang.String getMake() {
        java.lang.Object ref = make_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          make_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string make = 1;</code>
       * @return The bytes for make.
       */
      public com.google.protobuf.ByteString
          getMakeBytes() {
        java.lang.Object ref = make_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          make_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string make = 1;</code>
       * @param value The make to set.
       * @return This builder for chaining.
       */
      public Builder setMake(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        make_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string make = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMake() {
        
        make_ = getDefaultInstance().getMake();
        onChanged();
        return this;
      }
      /**
       * <code>string make = 1;</code>
       * @param value The bytes for make to set.
       * @return This builder for chaining.
       */
      public Builder setMakeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        make_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object model_ = "";
      /**
       * <code>string model = 2;</code>
       * @return The model.
       */
      public java.lang.String getModel() {
        java.lang.Object ref = model_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          model_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string model = 2;</code>
       * @return The bytes for model.
       */
      public com.google.protobuf.ByteString
          getModelBytes() {
        java.lang.Object ref = model_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          model_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string model = 2;</code>
       * @param value The model to set.
       * @return This builder for chaining.
       */
      public Builder setModel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        model_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string model = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearModel() {
        
        model_ = getDefaultInstance().getModel();
        onChanged();
        return this;
      }
      /**
       * <code>string model = 2;</code>
       * @param value The bytes for model to set.
       * @return This builder for chaining.
       */
      public Builder setModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        model_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object trim_ = "";
      /**
       * <code>string trim = 3;</code>
       * @return The trim.
       */
      public java.lang.String getTrim() {
        java.lang.Object ref = trim_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          trim_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string trim = 3;</code>
       * @return The bytes for trim.
       */
      public com.google.protobuf.ByteString
          getTrimBytes() {
        java.lang.Object ref = trim_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          trim_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string trim = 3;</code>
       * @param value The trim to set.
       * @return This builder for chaining.
       */
      public Builder setTrim(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        trim_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string trim = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTrim() {
        
        trim_ = getDefaultInstance().getTrim();
        onChanged();
        return this;
      }
      /**
       * <code>string trim = 3;</code>
       * @param value The bytes for trim to set.
       * @return This builder for chaining.
       */
      public Builder setTrimBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        trim_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object color_ = "";
      /**
       * <code>string color = 4;</code>
       * @return The color.
       */
      public java.lang.String getColor() {
        java.lang.Object ref = color_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          color_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string color = 4;</code>
       * @return The bytes for color.
       */
      public com.google.protobuf.ByteString
          getColorBytes() {
        java.lang.Object ref = color_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          color_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string color = 4;</code>
       * @param value The color to set.
       * @return This builder for chaining.
       */
      public Builder setColor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        color_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string color = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearColor() {
        
        color_ = getDefaultInstance().getColor();
        onChanged();
        return this;
      }
      /**
       * <code>string color = 4;</code>
       * @param value The bytes for color to set.
       * @return This builder for chaining.
       */
      public Builder setColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        color_ = value;
        onChanged();
        return this;
      }

      private int year_ ;
      /**
       * <code>uint32 year = 5;</code>
       * @return The year.
       */
      @java.lang.Override
      public int getYear() {
        return year_;
      }
      /**
       * <code>uint32 year = 5;</code>
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(int value) {
        
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 year = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearYear() {
        
        year_ = 0;
        onChanged();
        return this;
      }

      private int mileage_ ;
      /**
       * <code>uint32 mileage = 6;</code>
       * @return The mileage.
       */
      @java.lang.Override
      public int getMileage() {
        return mileage_;
      }
      /**
       * <code>uint32 mileage = 6;</code>
       * @param value The mileage to set.
       * @return This builder for chaining.
       */
      public Builder setMileage(int value) {
        
        mileage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 mileage = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMileage() {
        
        mileage_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.stevenpg.rvg.Message.Car)
    }

    // @@protoc_insertion_point(class_scope:com.stevenpg.rvg.Message.Car)
    private static final com.stevenpg.rvg.Message.Car DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stevenpg.rvg.Message.Car();
    }

    public static com.stevenpg.rvg.Message.Car getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Car>
        PARSER = new com.google.protobuf.AbstractParser<Car>() {
      @java.lang.Override
      public Car parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Car(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Car> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Car> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.stevenpg.rvg.Message.Car getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DriverOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stevenpg.rvg.Message.Driver)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string firstname = 1;</code>
     * @return The firstname.
     */
    java.lang.String getFirstname();
    /**
     * <code>string firstname = 1;</code>
     * @return The bytes for firstname.
     */
    com.google.protobuf.ByteString
        getFirstnameBytes();

    /**
     * <code>string lastname = 2;</code>
     * @return The lastname.
     */
    java.lang.String getLastname();
    /**
     * <code>string lastname = 2;</code>
     * @return The bytes for lastname.
     */
    com.google.protobuf.ByteString
        getLastnameBytes();

    /**
     * <code>string driverId = 3;</code>
     * @return The driverId.
     */
    java.lang.String getDriverId();
    /**
     * <code>string driverId = 3;</code>
     * @return The bytes for driverId.
     */
    com.google.protobuf.ByteString
        getDriverIdBytes();
  }
  /**
   * Protobuf type {@code com.stevenpg.rvg.Message.Driver}
   */
  public static final class Driver extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.stevenpg.rvg.Message.Driver)
      DriverOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Driver.newBuilder() to construct.
    private Driver(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Driver() {
      firstname_ = "";
      lastname_ = "";
      driverId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Driver();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Driver(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              firstname_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              lastname_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              driverId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stevenpg.rvg.MessageOuterClass.internal_static_com_stevenpg_rvg_Message_Driver_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stevenpg.rvg.MessageOuterClass.internal_static_com_stevenpg_rvg_Message_Driver_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stevenpg.rvg.Message.Driver.class, com.stevenpg.rvg.Message.Driver.Builder.class);
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object firstname_;
    /**
     * <code>string firstname = 1;</code>
     * @return The firstname.
     */
    @java.lang.Override
    public java.lang.String getFirstname() {
      java.lang.Object ref = firstname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstname_ = s;
        return s;
      }
    }
    /**
     * <code>string firstname = 1;</code>
     * @return The bytes for firstname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstnameBytes() {
      java.lang.Object ref = firstname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object lastname_;
    /**
     * <code>string lastname = 2;</code>
     * @return The lastname.
     */
    @java.lang.Override
    public java.lang.String getLastname() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastname_ = s;
        return s;
      }
    }
    /**
     * <code>string lastname = 2;</code>
     * @return The bytes for lastname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastnameBytes() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DRIVERID_FIELD_NUMBER = 3;
    private volatile java.lang.Object driverId_;
    /**
     * <code>string driverId = 3;</code>
     * @return The driverId.
     */
    @java.lang.Override
    public java.lang.String getDriverId() {
      java.lang.Object ref = driverId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        driverId_ = s;
        return s;
      }
    }
    /**
     * <code>string driverId = 3;</code>
     * @return The bytes for driverId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDriverIdBytes() {
      java.lang.Object ref = driverId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        driverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFirstnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstname_);
      }
      if (!getLastnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastname_);
      }
      if (!getDriverIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, driverId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFirstnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstname_);
      }
      if (!getLastnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastname_);
      }
      if (!getDriverIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, driverId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stevenpg.rvg.Message.Driver)) {
        return super.equals(obj);
      }
      com.stevenpg.rvg.Message.Driver other = (com.stevenpg.rvg.Message.Driver) obj;

      if (!getFirstname()
          .equals(other.getFirstname())) return false;
      if (!getLastname()
          .equals(other.getLastname())) return false;
      if (!getDriverId()
          .equals(other.getDriverId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstname().hashCode();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastname().hashCode();
      hash = (37 * hash) + DRIVERID_FIELD_NUMBER;
      hash = (53 * hash) + getDriverId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stevenpg.rvg.Message.Driver parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stevenpg.rvg.Message.Driver parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stevenpg.rvg.Message.Driver parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stevenpg.rvg.Message.Driver parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stevenpg.rvg.Message.Driver parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stevenpg.rvg.Message.Driver parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stevenpg.rvg.Message.Driver parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stevenpg.rvg.Message.Driver parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stevenpg.rvg.Message.Driver parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stevenpg.rvg.Message.Driver parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stevenpg.rvg.Message.Driver parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stevenpg.rvg.Message.Driver parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stevenpg.rvg.Message.Driver prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.stevenpg.rvg.Message.Driver}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stevenpg.rvg.Message.Driver)
        com.stevenpg.rvg.Message.DriverOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stevenpg.rvg.MessageOuterClass.internal_static_com_stevenpg_rvg_Message_Driver_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stevenpg.rvg.MessageOuterClass.internal_static_com_stevenpg_rvg_Message_Driver_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stevenpg.rvg.Message.Driver.class, com.stevenpg.rvg.Message.Driver.Builder.class);
      }

      // Construct using com.stevenpg.rvg.Message.Driver.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        firstname_ = "";

        lastname_ = "";

        driverId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stevenpg.rvg.MessageOuterClass.internal_static_com_stevenpg_rvg_Message_Driver_descriptor;
      }

      @java.lang.Override
      public com.stevenpg.rvg.Message.Driver getDefaultInstanceForType() {
        return com.stevenpg.rvg.Message.Driver.getDefaultInstance();
      }

      @java.lang.Override
      public com.stevenpg.rvg.Message.Driver build() {
        com.stevenpg.rvg.Message.Driver result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.stevenpg.rvg.Message.Driver buildPartial() {
        com.stevenpg.rvg.Message.Driver result = new com.stevenpg.rvg.Message.Driver(this);
        result.firstname_ = firstname_;
        result.lastname_ = lastname_;
        result.driverId_ = driverId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stevenpg.rvg.Message.Driver) {
          return mergeFrom((com.stevenpg.rvg.Message.Driver)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stevenpg.rvg.Message.Driver other) {
        if (other == com.stevenpg.rvg.Message.Driver.getDefaultInstance()) return this;
        if (!other.getFirstname().isEmpty()) {
          firstname_ = other.firstname_;
          onChanged();
        }
        if (!other.getLastname().isEmpty()) {
          lastname_ = other.lastname_;
          onChanged();
        }
        if (!other.getDriverId().isEmpty()) {
          driverId_ = other.driverId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stevenpg.rvg.Message.Driver parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stevenpg.rvg.Message.Driver) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object firstname_ = "";
      /**
       * <code>string firstname = 1;</code>
       * @return The firstname.
       */
      public java.lang.String getFirstname() {
        java.lang.Object ref = firstname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string firstname = 1;</code>
       * @return The bytes for firstname.
       */
      public com.google.protobuf.ByteString
          getFirstnameBytes() {
        java.lang.Object ref = firstname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string firstname = 1;</code>
       * @param value The firstname to set.
       * @return This builder for chaining.
       */
      public Builder setFirstname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string firstname = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstname() {
        
        firstname_ = getDefaultInstance().getFirstname();
        onChanged();
        return this;
      }
      /**
       * <code>string firstname = 1;</code>
       * @param value The bytes for firstname to set.
       * @return This builder for chaining.
       */
      public Builder setFirstnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastname_ = "";
      /**
       * <code>string lastname = 2;</code>
       * @return The lastname.
       */
      public java.lang.String getLastname() {
        java.lang.Object ref = lastname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lastname = 2;</code>
       * @return The bytes for lastname.
       */
      public com.google.protobuf.ByteString
          getLastnameBytes() {
        java.lang.Object ref = lastname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lastname = 2;</code>
       * @param value The lastname to set.
       * @return This builder for chaining.
       */
      public Builder setLastname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lastname = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastname() {
        
        lastname_ = getDefaultInstance().getLastname();
        onChanged();
        return this;
      }
      /**
       * <code>string lastname = 2;</code>
       * @param value The bytes for lastname to set.
       * @return This builder for chaining.
       */
      public Builder setLastnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object driverId_ = "";
      /**
       * <code>string driverId = 3;</code>
       * @return The driverId.
       */
      public java.lang.String getDriverId() {
        java.lang.Object ref = driverId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          driverId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string driverId = 3;</code>
       * @return The bytes for driverId.
       */
      public com.google.protobuf.ByteString
          getDriverIdBytes() {
        java.lang.Object ref = driverId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          driverId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string driverId = 3;</code>
       * @param value The driverId to set.
       * @return This builder for chaining.
       */
      public Builder setDriverId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        driverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string driverId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDriverId() {
        
        driverId_ = getDefaultInstance().getDriverId();
        onChanged();
        return this;
      }
      /**
       * <code>string driverId = 3;</code>
       * @param value The bytes for driverId to set.
       * @return This builder for chaining.
       */
      public Builder setDriverIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        driverId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.stevenpg.rvg.Message.Driver)
    }

    // @@protoc_insertion_point(class_scope:com.stevenpg.rvg.Message.Driver)
    private static final com.stevenpg.rvg.Message.Driver DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stevenpg.rvg.Message.Driver();
    }

    public static com.stevenpg.rvg.Message.Driver getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Driver>
        PARSER = new com.google.protobuf.AbstractParser<Driver>() {
      @java.lang.Override
      public Driver parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Driver(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Driver> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Driver> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.stevenpg.rvg.Message.Driver getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int CAR_FIELD_NUMBER = 1;
  private com.stevenpg.rvg.Message.Car car_;
  /**
   * <code>.com.stevenpg.rvg.Message.Car car = 1;</code>
   * @return Whether the car field is set.
   */
  @java.lang.Override
  public boolean hasCar() {
    return car_ != null;
  }
  /**
   * <code>.com.stevenpg.rvg.Message.Car car = 1;</code>
   * @return The car.
   */
  @java.lang.Override
  public com.stevenpg.rvg.Message.Car getCar() {
    return car_ == null ? com.stevenpg.rvg.Message.Car.getDefaultInstance() : car_;
  }
  /**
   * <code>.com.stevenpg.rvg.Message.Car car = 1;</code>
   */
  @java.lang.Override
  public com.stevenpg.rvg.Message.CarOrBuilder getCarOrBuilder() {
    return getCar();
  }

  public static final int DRIVER_FIELD_NUMBER = 2;
  private com.stevenpg.rvg.Message.Driver driver_;
  /**
   * <code>.com.stevenpg.rvg.Message.Driver driver = 2;</code>
   * @return Whether the driver field is set.
   */
  @java.lang.Override
  public boolean hasDriver() {
    return driver_ != null;
  }
  /**
   * <code>.com.stevenpg.rvg.Message.Driver driver = 2;</code>
   * @return The driver.
   */
  @java.lang.Override
  public com.stevenpg.rvg.Message.Driver getDriver() {
    return driver_ == null ? com.stevenpg.rvg.Message.Driver.getDefaultInstance() : driver_;
  }
  /**
   * <code>.com.stevenpg.rvg.Message.Driver driver = 2;</code>
   */
  @java.lang.Override
  public com.stevenpg.rvg.Message.DriverOrBuilder getDriverOrBuilder() {
    return getDriver();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (car_ != null) {
      output.writeMessage(1, getCar());
    }
    if (driver_ != null) {
      output.writeMessage(2, getDriver());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (car_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCar());
    }
    if (driver_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDriver());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stevenpg.rvg.Message)) {
      return super.equals(obj);
    }
    com.stevenpg.rvg.Message other = (com.stevenpg.rvg.Message) obj;

    if (hasCar() != other.hasCar()) return false;
    if (hasCar()) {
      if (!getCar()
          .equals(other.getCar())) return false;
    }
    if (hasDriver() != other.hasDriver()) return false;
    if (hasDriver()) {
      if (!getDriver()
          .equals(other.getDriver())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCar()) {
      hash = (37 * hash) + CAR_FIELD_NUMBER;
      hash = (53 * hash) + getCar().hashCode();
    }
    if (hasDriver()) {
      hash = (37 * hash) + DRIVER_FIELD_NUMBER;
      hash = (53 * hash) + getDriver().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stevenpg.rvg.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stevenpg.rvg.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stevenpg.rvg.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stevenpg.rvg.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stevenpg.rvg.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stevenpg.rvg.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stevenpg.rvg.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stevenpg.rvg.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stevenpg.rvg.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stevenpg.rvg.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stevenpg.rvg.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stevenpg.rvg.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stevenpg.rvg.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.stevenpg.rvg.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.stevenpg.rvg.Message)
      com.stevenpg.rvg.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stevenpg.rvg.MessageOuterClass.internal_static_com_stevenpg_rvg_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stevenpg.rvg.MessageOuterClass.internal_static_com_stevenpg_rvg_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stevenpg.rvg.Message.class, com.stevenpg.rvg.Message.Builder.class);
    }

    // Construct using com.stevenpg.rvg.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (carBuilder_ == null) {
        car_ = null;
      } else {
        car_ = null;
        carBuilder_ = null;
      }
      if (driverBuilder_ == null) {
        driver_ = null;
      } else {
        driver_ = null;
        driverBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stevenpg.rvg.MessageOuterClass.internal_static_com_stevenpg_rvg_Message_descriptor;
    }

    @java.lang.Override
    public com.stevenpg.rvg.Message getDefaultInstanceForType() {
      return com.stevenpg.rvg.Message.getDefaultInstance();
    }

    @java.lang.Override
    public com.stevenpg.rvg.Message build() {
      com.stevenpg.rvg.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stevenpg.rvg.Message buildPartial() {
      com.stevenpg.rvg.Message result = new com.stevenpg.rvg.Message(this);
      if (carBuilder_ == null) {
        result.car_ = car_;
      } else {
        result.car_ = carBuilder_.build();
      }
      if (driverBuilder_ == null) {
        result.driver_ = driver_;
      } else {
        result.driver_ = driverBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stevenpg.rvg.Message) {
        return mergeFrom((com.stevenpg.rvg.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stevenpg.rvg.Message other) {
      if (other == com.stevenpg.rvg.Message.getDefaultInstance()) return this;
      if (other.hasCar()) {
        mergeCar(other.getCar());
      }
      if (other.hasDriver()) {
        mergeDriver(other.getDriver());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stevenpg.rvg.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stevenpg.rvg.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.stevenpg.rvg.Message.Car car_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stevenpg.rvg.Message.Car, com.stevenpg.rvg.Message.Car.Builder, com.stevenpg.rvg.Message.CarOrBuilder> carBuilder_;
    /**
     * <code>.com.stevenpg.rvg.Message.Car car = 1;</code>
     * @return Whether the car field is set.
     */
    public boolean hasCar() {
      return carBuilder_ != null || car_ != null;
    }
    /**
     * <code>.com.stevenpg.rvg.Message.Car car = 1;</code>
     * @return The car.
     */
    public com.stevenpg.rvg.Message.Car getCar() {
      if (carBuilder_ == null) {
        return car_ == null ? com.stevenpg.rvg.Message.Car.getDefaultInstance() : car_;
      } else {
        return carBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.stevenpg.rvg.Message.Car car = 1;</code>
     */
    public Builder setCar(com.stevenpg.rvg.Message.Car value) {
      if (carBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        car_ = value;
        onChanged();
      } else {
        carBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.stevenpg.rvg.Message.Car car = 1;</code>
     */
    public Builder setCar(
        com.stevenpg.rvg.Message.Car.Builder builderForValue) {
      if (carBuilder_ == null) {
        car_ = builderForValue.build();
        onChanged();
      } else {
        carBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.stevenpg.rvg.Message.Car car = 1;</code>
     */
    public Builder mergeCar(com.stevenpg.rvg.Message.Car value) {
      if (carBuilder_ == null) {
        if (car_ != null) {
          car_ =
            com.stevenpg.rvg.Message.Car.newBuilder(car_).mergeFrom(value).buildPartial();
        } else {
          car_ = value;
        }
        onChanged();
      } else {
        carBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.stevenpg.rvg.Message.Car car = 1;</code>
     */
    public Builder clearCar() {
      if (carBuilder_ == null) {
        car_ = null;
        onChanged();
      } else {
        car_ = null;
        carBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.stevenpg.rvg.Message.Car car = 1;</code>
     */
    public com.stevenpg.rvg.Message.Car.Builder getCarBuilder() {
      
      onChanged();
      return getCarFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.stevenpg.rvg.Message.Car car = 1;</code>
     */
    public com.stevenpg.rvg.Message.CarOrBuilder getCarOrBuilder() {
      if (carBuilder_ != null) {
        return carBuilder_.getMessageOrBuilder();
      } else {
        return car_ == null ?
            com.stevenpg.rvg.Message.Car.getDefaultInstance() : car_;
      }
    }
    /**
     * <code>.com.stevenpg.rvg.Message.Car car = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stevenpg.rvg.Message.Car, com.stevenpg.rvg.Message.Car.Builder, com.stevenpg.rvg.Message.CarOrBuilder> 
        getCarFieldBuilder() {
      if (carBuilder_ == null) {
        carBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.stevenpg.rvg.Message.Car, com.stevenpg.rvg.Message.Car.Builder, com.stevenpg.rvg.Message.CarOrBuilder>(
                getCar(),
                getParentForChildren(),
                isClean());
        car_ = null;
      }
      return carBuilder_;
    }

    private com.stevenpg.rvg.Message.Driver driver_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stevenpg.rvg.Message.Driver, com.stevenpg.rvg.Message.Driver.Builder, com.stevenpg.rvg.Message.DriverOrBuilder> driverBuilder_;
    /**
     * <code>.com.stevenpg.rvg.Message.Driver driver = 2;</code>
     * @return Whether the driver field is set.
     */
    public boolean hasDriver() {
      return driverBuilder_ != null || driver_ != null;
    }
    /**
     * <code>.com.stevenpg.rvg.Message.Driver driver = 2;</code>
     * @return The driver.
     */
    public com.stevenpg.rvg.Message.Driver getDriver() {
      if (driverBuilder_ == null) {
        return driver_ == null ? com.stevenpg.rvg.Message.Driver.getDefaultInstance() : driver_;
      } else {
        return driverBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.stevenpg.rvg.Message.Driver driver = 2;</code>
     */
    public Builder setDriver(com.stevenpg.rvg.Message.Driver value) {
      if (driverBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        driver_ = value;
        onChanged();
      } else {
        driverBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.stevenpg.rvg.Message.Driver driver = 2;</code>
     */
    public Builder setDriver(
        com.stevenpg.rvg.Message.Driver.Builder builderForValue) {
      if (driverBuilder_ == null) {
        driver_ = builderForValue.build();
        onChanged();
      } else {
        driverBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.stevenpg.rvg.Message.Driver driver = 2;</code>
     */
    public Builder mergeDriver(com.stevenpg.rvg.Message.Driver value) {
      if (driverBuilder_ == null) {
        if (driver_ != null) {
          driver_ =
            com.stevenpg.rvg.Message.Driver.newBuilder(driver_).mergeFrom(value).buildPartial();
        } else {
          driver_ = value;
        }
        onChanged();
      } else {
        driverBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.stevenpg.rvg.Message.Driver driver = 2;</code>
     */
    public Builder clearDriver() {
      if (driverBuilder_ == null) {
        driver_ = null;
        onChanged();
      } else {
        driver_ = null;
        driverBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.stevenpg.rvg.Message.Driver driver = 2;</code>
     */
    public com.stevenpg.rvg.Message.Driver.Builder getDriverBuilder() {
      
      onChanged();
      return getDriverFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.stevenpg.rvg.Message.Driver driver = 2;</code>
     */
    public com.stevenpg.rvg.Message.DriverOrBuilder getDriverOrBuilder() {
      if (driverBuilder_ != null) {
        return driverBuilder_.getMessageOrBuilder();
      } else {
        return driver_ == null ?
            com.stevenpg.rvg.Message.Driver.getDefaultInstance() : driver_;
      }
    }
    /**
     * <code>.com.stevenpg.rvg.Message.Driver driver = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stevenpg.rvg.Message.Driver, com.stevenpg.rvg.Message.Driver.Builder, com.stevenpg.rvg.Message.DriverOrBuilder> 
        getDriverFieldBuilder() {
      if (driverBuilder_ == null) {
        driverBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.stevenpg.rvg.Message.Driver, com.stevenpg.rvg.Message.Driver.Builder, com.stevenpg.rvg.Message.DriverOrBuilder>(
                getDriver(),
                getParentForChildren(),
                isClean());
        driver_ = null;
      }
      return driverBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.stevenpg.rvg.Message)
  }

  // @@protoc_insertion_point(class_scope:com.stevenpg.rvg.Message)
  private static final com.stevenpg.rvg.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stevenpg.rvg.Message();
  }

  public static com.stevenpg.rvg.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stevenpg.rvg.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

