// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.stevenpg.rvg;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stevenpg.rvg.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.stevenpg.rvg.Message.Car car = 1;</code>
   * @return Whether the car field is set.
   */
  boolean hasCar();
  /**
   * <code>.com.stevenpg.rvg.Message.Car car = 1;</code>
   * @return The car.
   */
  com.stevenpg.rvg.Message.Car getCar();
  /**
   * <code>.com.stevenpg.rvg.Message.Car car = 1;</code>
   */
  com.stevenpg.rvg.Message.CarOrBuilder getCarOrBuilder();

  /**
   * <code>.com.stevenpg.rvg.Message.Driver driver = 2;</code>
   * @return Whether the driver field is set.
   */
  boolean hasDriver();
  /**
   * <code>.com.stevenpg.rvg.Message.Driver driver = 2;</code>
   * @return The driver.
   */
  com.stevenpg.rvg.Message.Driver getDriver();
  /**
   * <code>.com.stevenpg.rvg.Message.Driver driver = 2;</code>
   */
  com.stevenpg.rvg.Message.DriverOrBuilder getDriverOrBuilder();
}
