// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.stevenpg.rvg;

public interface ResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stevenpg.rvg.Result)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
